/**
 * SampleBackEndTemplate
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateMemberCommand { 
    id?: number;
    firstName?: string;
    middleName?: string;
    lastName?: string;
    suffixName?: string;
    province?: string;
    city?: string;
    barangay?: string;
    emailAddress?: string;
    phoneNumber?: string;
    birthdate?: Date;
    age?: number;
    gender?: string;
    zipCode?: string;
}